[package]
name = "ncf_rnn"
version = "0.0.0"
authors = ["Andrew <andrew@subarctic.org>"]
license = "MIT OR Apache-2.0"
edition = "2018"
readme = "README.md"

[dependencies]
autograd = { version = "1.1.0", features = ["mkl"] }
